const $=q=>document.querySelector(q),R=(a,b)=>a+Math.random()*(b-a),esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const fmt=n=>(n<0?'-':'')+Math.abs(Math.round(n)).toLocaleString('vi-VN')+'đ',cl=v=>Math.max(0,Math.min(100,v));
const PL={home:['🏠','Nhà','#cfe3f7','🛋️'],office:['🏢','Công ty','#d7d3f5','🖥️'],school:['🏫','Trường học','#fde6b8','📚'],market:['🛒','Siêu thị','#d4f1de','🥬'],shop:['🏪','Cửa hàng','#ffe0d6','📦'],restaurant:['🍜','Nhà hàng','#ffe9c7','🍲'],cafe:['☕','Cafe','#ecdcca','☕'],park:['🌳','Công viên','#cdeccb','🌳'],hospital:['🏥','Bệnh viện','#f3d9e0','💉'],station:['🚆','Ga tàu','#d9e2ee','🚆'],airport:['✈️','Sân bay','#cfe6f5','✈️'],mall:['🏬','TTTM','#f1dcf5','🛍️'],street:['🛣️','Đường phố','#dfe4ea','🚗']};
const ICON={eat30:'🍜',eat60:'🍱',cook:'🍳',cafe:'☕',tv:'📺',game:'🎮',park:'🌳',sleep:'😴',read:'📖',travel:'✈️',work:'💼',friends:'👯'};
const ST=[['money','💰'],['health','❤️'],['mood','😊'],['energy','⚡'],['hunger','🍔'],['skill','🧠'],['social','👥'],['rep','⭐']];
let D={},S=null,tab='home',card=null,idea=null,ideaOpen=false,toast='';
const J=id=>(S.custom.jobs.find(j=>j.id==id))||D.jobs[id];
const has=p=>S.inv.some(i=>i.id.startsWith(p)&&!i.broken);
const P=n=>S.people.find(p=>p.n==n);
const clock=()=>{const h=Math.floor(S.hour),m=S.hour%1?'30':'00';return `${String(h%12||12).padStart(2,'0')}:${m} ${h<12?'AM':'PM'}`};
function log(t){S.log.unshift(`Ngày ${S.day} ${clock()} — ${t}`);S.log=S.log.slice(0,60);S.story=t}
function fx(o){for(const k in o){if(k=='money')S.money+=o[k];else S.st[k]=cl(S.st[k]+o[k])}}
function tick(h){S.hour+=h;fx({hunger:-2*h});while(S.hour>=24){S.hour-=24;S.day++;let c=D.homes.find(x=>x.id==S.home).rent+(S.flags.shopOpen?150000:0);S.money-=c;log(`Qua ngày mới. Tiền thuê ${fmt(c)}.`);if(S.money<0)fx({mood:-5})}
if(S.st.hunger<15)fx({health:-4,mood:-3});if(S.st.energy<15)fx({mood:-3});if(S.st.health<=0){S.money-=500000;S.st.health=40;S.place='hospital';log('Bạn ngất xỉu, nhập viện. Viện phí 500.000đ.')}}
// ===== SỰ KIỆN: phụ thuộc tuổi, tiền, nghề, nơi, quan hệ, tính cách, lịch sử =====
const EV=[
{id:'phone',w:()=>9,ok:()=>S.inv.some(i=>i.id.startsWith('phone')&&!i.broken&&!i.chk&&S.day-i.day>=3),pre(){S.inv.find(i=>i.id.startsWith('phone')&&!i.chk).chk=1;this.it=S.inv.find(i=>i.chk&&!i.broken&&i.id.startsWith('phone'))},ic:'📱',t:()=>'Điện thoại của bạn bị hỏng!',ch:[['Sửa',()=>{const c=has('phone2')?1500000:600000;S.money-=c;return`Bạn sửa điện thoại, mất ${fmt(c)}.`}],['Không sửa',()=>{S.inv.filter(i=>i.id.startsWith('phone')).forEach(i=>i.broken=1);fx({mood:-4});return'Bạn dùng tạm, tiện ích giảm.'}],['Mua máy mới (2.5tr)',()=>{S.inv=S.inv.filter(i=>!i.id.startsWith('phone'));S.inv.push({id:'phone1',n:'Điện thoại phổ thông',day:S.day});S.money-=2500000;return'Bạn mua máy mới, tốn khá nhiều.'}],['Tự sửa (cần skill 8)',()=>{if(S.st.skill>=8){fx({skill:2});return'Bạn tự sửa thành công!'}S.money-=200000;fx({mood:-3});return'Tự sửa thất bại, mất 200.000đ linh kiện.'}]]},
{id:'raise',w:()=>10,ok:()=>S.job=='office'&&S.shifts>=5&&!S.flags.raised&&(S.flags.pen||0)<2,ic:'💰',t:()=>'Anh Hùng gọi bạn vào phòng: "Em làm tốt. Tăng lương 30%!"',ch:[['Cảm ơn sếp',()=>{S.flags.raised=1;S.payMul=1.3;fx({rep:5,mood:8});P('Anh Hùng').rel+=10;return'Lương tăng lên 30%!'}]]},
{id:'warn',w:()=>10,ok:()=>S.job=='office'&&(S.flags.pen||0)>=2&&!S.flags.warned,ic:'⚠️',t:()=>'Sếp nhắc bạn đi trễ quá nhiều.',ch:[['Xin lỗi, hứa sửa',()=>{S.flags.warned=1;S.flags.pen=0;P('Anh Hùng').rel+=3;return'Sếp bỏ qua lần này.'}],['Cãi lại',()=>{S.flags.warned=1;P('Anh Hùng').rel-=15;fx({rep:-5,mood:-5});return'Quan hệ với sếp xấu đi.'}]]},
{id:'friend',w:()=>6,ok:()=>S.place=='cafe'&&S.st.social>=10,ic:'☕',t:()=>'Bạn gặp một người bạn cũ. "Đã lâu không gặp!"',ch:[['Nói chuyện',()=>{fx({social:6,mood:5});add('Minh','Bạn cũ');return'Hai bạn hàn huyên vui vẻ.'}],['Đi tiếp',()=>'Bạn mỉm cười rồi đi tiếp.'],['Mời cafe (40k)',()=>{S.money-=40000;fx({social:8,mood:6});add('Minh','Bạn cũ').rel+=10;return'Minh rất vui vì được mời.'}],['Hỏi công việc',()=>{add('Minh','Bạn cũ');if(S.job=='none'){S.flags.lead=1;return'Minh hứa giới thiệu bạn đi phỏng vấn.'}return'Minh chia sẻ kinh nghiệm làm việc (+skill).'}]]},
{id:'interview',w:()=>9,ok:()=>S.job=='none'&&(S.flags.lead||S.st.skill>=3),ic:'📩',t:()=>'Bạn được mời phỏng vấn vị trí nhân viên văn phòng.',ch:[['Đi phỏng vấn',()=>{if(Math.random()<.5+S.st.skill/40+(S.flags.lead?.2:0)){S.job='office';S.shifts=0;S.payMul=1;return'Bạn trúng tuyển! Bắt đầu đi làm tại công ty.'}fx({mood:-4});return'Bạn chưa được nhận lần này.'}],['Từ chối',()=>'Bạn bỏ qua cơ hội.']]},
{id:'found',w:()=>6,ok:()=>S.place=='street',ic:'💵',t:()=>'Bạn thấy một xấp tiền rơi trên đường.',ch:[['Giữ lại',()=>{S.money+=150000;fx({rep:-2});return'Bạn nhặt được 150.000đ.'}],['Trả lại công an',()=>{fx({rep:5,mood:3});return'Bạn được khen ngợi.'}]]},
{id:'invite',w:()=>S.traits.includes('Hướng ngoại')?10:5,ok:()=>S.st.social>=10&&S.hour>=16,ic:'🎉',t:()=>'Linh nhắn: "Tối nay đi chơi không?"',ch:[['Đi (100k)',()=>{S.money-=100000;fx({mood:10,social:8,energy:-10});P('Linh').rel+=6;return'Bạn có một buổi tối vui.'}],['Để hôm khác',()=>{P('Linh').rel-=2;return'Linh hơi tiếc.'}]]},
{id:'help',w:()=>6,ok:()=>P('Linh').rel>=40&&S.money>300000,ic:'🆘',t:()=>'Linh cần bạn giúp 200k tiền gấp.',ch:[['Giúp',()=>{S.money-=200000;P('Linh').rel+=10;fx({rep:2});return'Linh biết ơn bạn lắm.'}],['Từ chối',()=>{P('Linh').rel-=8;return'Linh có vẻ buồn.'}]]},
{id:'mom',w:()=>5,ok:()=>true,ic:'📞',t:()=>'Mẹ gọi hỏi thăm bạn.',ch:[['Nghe máy',()=>{P('Mẹ').rel+=5;fx({mood:4});return'Mẹ dặn bạn ăn uống đầy đủ.'}],['Bỏ qua',()=>{P('Mẹ').rel-=6;return'Mẹ hơi buồn.'}]]},
{id:'biz',w:()=>S.traits.includes('Liều lĩnh')?10:4,ok:()=>S.money>=2000000&&!S.flags.shopOpen&&!S.flags.deal,ic:'🏪',t:()=>'Bạn nghe có mặt bằng cửa hàng giá rẻ.',ch:[['Quan tâm',()=>{S.flags.deal=1;return'Mở cửa hàng được giảm giá còn 2tr (Tab LIFE).'}],['Bỏ qua',()=>'Bạn bỏ qua.']]},
{id:'lost',w:()=>3,ok:()=>S.place=='market'||S.place=='mall',ic:'😱',t:()=>'Bạn phát hiện mất ví!',ch:[['Quay lại tìm',()=>{if(Math.random()<.5){return'Tìm lại được ví!'}S.money-=Math.min(S.money,100000);return'Mất 100.000đ.'}],['Kệ',()=>{S.money-=Math.min(S.money,100000);fx({mood:-4});return'Bạn mất 100.000đ.'}]]}];
function add(n,role){let p=P(n);if(!p){p={n,role,age:Math.round(R(20,40)),tr:'thân thiện',rel:40,mood:'ổn',mem:[]};S.people.push(p)}return p}
function afterAct(){S.n++;if(S.n%8==0)return card={ic:'💡',t:'Bạn muốn thêm gì vào thế giới này?',ch:[['Mở IDEA BOX',()=>{ideaOpen=true;return''}],['Để sau',()=>'']]};
if(Math.random()<.45){const ok=EV.filter(e=>(S.cd[e.id]||-9)<S.day-1&&e.ok());const c=S.custom.events.find(e=>!e.done&&Math.random()<.2);
if(c){c.done=1;card={ic:'🎁',t:c.name+' — '+c.desc,ch:[['OK',()=>{fx({mood:c.mood||3});return'Sự kiện do bạn tạo xảy ra.'}]]};return}
if(ok.length){let t=ok.reduce((a,e)=>a+e.w(),0)*Math.random();const e=ok.find(e=>(t-=e.w())<=0)||ok[0];S.cd[e.id]=S.day;e.pre&&e.pre();card={ic:e.ic,t:e.t(),ch:e.ch,place:S.place}}}}
function pick(i){const r=card.ch[i][1]();const was=card;card=null;if(r)log(r);afterAct0();save(1);render()}
function afterAct0(){}
// ===== HÀNH ĐỘNG =====
function go(p,story){const far=['airport','mall','hospital'].includes(p);let c=0,h=.5;if(has('bike')){c=5000}else if(far){c=7000;h=1.5}if(far&&S.place!=p&&!has('bike')&&S.money<c)return say('Không đủ tiền đi xe.');
S.money-=c;S.place=p;tick(h);log(story||`Bạn đến ${PL[p][1]}${c?' ('+fmt(c)+')':''}.`);afterAct();render()}
function say(t){toast=t;render();setTimeout(()=>{toast='';render()},1800)}
function act(id){const a=D.acts.find(x=>x.id==id);if(S.money+a.m<0)return say('Không đủ tiền!');S.money+=a.m;fx(a.fx);if(a.flag)S.flags.food=(S.flags.food||0)+3;
if(a.rel){const p=P(a.rel);if(p){p.rel+=5;p.mem.push('Đi chơi (ngày '+S.day+')')}}S.last=id;tick(a.h);log(a.t);afterAct();save(1);render()}
function work(){const j=J(S.job);if(!j||!j.pay)return say('Bạn chưa có việc.');if(S.place!=j.at)return say('Hãy đến '+PL[j.at][1]+' trước.');if(j.need&&!has(j.need))return say('Cần mua '+(j.need=='laptop'?'laptop':j.need));
if(j.stock&&!(S.flags.food2>0))return say('Hết hàng! Hãy nhập hàng (Tab LIFE).');let pay,t;
if(S.job=='office'){pay=j.pay[0]*(S.payMul||1);t='Bạn làm ca ở văn phòng.';if(S.hour>9){pay-=100000;S.flags.pen=(S.flags.pen||0)+1;t+=' Đi trễ nên bị phạt 100.000đ.'}}
else if(S.job=='shop'){S.flags.food2--;pay=R(0,j.pay[1])-100000;t=pay>0?'Hôm nay khách đông.':'Hôm nay ế khách, bạn lỗ.'}
else{pay=R(j.pay[0],j.pay[1])*(1+S.st.skill/60);t='Bạn hoàn thành công việc.'}
if(S.st.energy<30){pay-=100000;fx({rep:-2});t+=' Bạn mệt nên mắc lỗi.'}
S.shifts++;S.money+=pay;fx({energy:-j.en,hunger:-8,skill:1,rep:1});S.last='work';tick(j.h);log(`${t} ${pay>=0?'+':''}${fmt(pay)}.`);afterAct();save(1);render()}
function life(k){if(k=='job'){if(S.job!='none')return say('Bạn đang có việc.');if(S.st.skill>=3||Math.random()<.5){S.job='office';S.shifts=0;S.payMul=1;log('Bạn được nhận làm văn phòng!')}else{fx({mood:-3,skill:1});log('Bạn bị từ chối nhưng học được kinh nghiệm.')}}
else if(k=='free'){if(!has('laptop'))return say('Cần laptop.');S.job='freelancer';log('Bạn bắt đầu nhận dự án freelance.')}
else if(k=='open'){const c=S.flags.deal?2000000:3000000;if(S.money<c)return say('Cần '+fmt(c));S.money-=c;S.flags.shopOpen=1;S.job='shop';S.flags.food2=0;log('Bạn mở cửa hàng! Tiền thuê 150.000đ/ngày.')}
else if(k=='stock'){if(!S.flags.shopOpen)return say('Chưa có cửa hàng.');if(S.money<300000)return say('Cần 300.000đ');S.money-=300000;S.flags.food2=(S.flags.food2||0)+3;log('Bạn nhập hàng đủ cho 3 ca.')}
else if(k=='learn'){if(S.money<300000)return say('Cần 300.000đ');S.money-=300000;fx({skill:6,energy:-10});tick(3);log('Bạn học nghề, kỹ năng tăng.')}
else if(k=='quit'){if(S.job=='none')return;if(S.job=='office'){P('Anh Hùng').rel-=5}S.job='none';fx({mood:5});log('Bạn nghỉ việc.')}
else if(k=='part'){S.money+=150000;fx({energy:-15,hunger:-8});tick(4);log('Bạn làm thêm 4 giờ, nhận 150.000đ.')}
else if(k.startsWith('c:')){S.job=k.slice(2);log('Bạn nhận nghề mới: '+J(S.job).n)}
afterAct();save(1);render()}
function buy(id){const it=[...D.shop,...S.custom.items].find(x=>x.id==id);if(S.money<it.p)return say('Không đủ tiền!');S.money-=it.p;if(id!='gift')S.inv.push({id,n:it.n,day:S.day});else S.flags.gift=(S.flags.gift||0)+1;fx(it.fx||{});S.last='shop';log(`Bạn mua ${it.n} (${fmt(it.p)}).`);afterAct();save(1);render()}
function rent(id){const h=D.homes.find(x=>x.id==id),d=h.rent*5;if(S.money<d)return say('Cần đặt cọc '+fmt(d));S.money-=d;S.home=id;log(`Bạn thuê ${h.n}, cọc ${fmt(d)}.`);afterAct();save(1);render()}
function talk(n,k){const p=P(n);let t;
if(k=='talk'){p.rel+=p.mood=='giận'?-2:4;fx({social:2,mood:2});t=`Bạn trò chuyện với ${n}.`}
if(k=='gift'){if(S.flags.gift>0)S.flags.gift--;else if(S.money>=100000)S.money-=100000;else return say('Không đủ tiền!');p.rel+=8;p.mood='vui';t=`${n} rất vui khi nhận quà.`}
if(k=='out'){if(S.money<100000)return say('Cần 100.000đ');S.money-=100000;p.rel+=6;fx({mood:8,social:6});tick(2);t=`Bạn đi chơi cùng ${n}.`}
if(k=='help'){p.rel+=5;fx({rep:2,energy:-8});tick(1);t=`Bạn giúp đỡ ${n}.`}
if(k=='argue'){p.rel-=12;p.mood='giận';fx({mood:-4});t=`Bạn tranh luận với ${n}. Họ giận.`}
if(k=='sorry'){if(p.mood=='giận'){p.rel+=8;p.mood='ổn';t=`${n} chấp nhận lời xin lỗi.`}else t=`${n} bối rối vì lời xin lỗi.`}
if(k=='date'){if(p.rel<75)return say('Cần quan hệ ≥ 75');p.role='Người yêu';p.rel+=5;t=`Bạn và ${n} bắt đầu hẹn hò!`}
p.rel=Math.max(0,Math.min(100,p.rel));p.mem.push(k+' (ngày '+S.day+')');p.mem=p.mem.slice(-5);log(t);afterAct();save(1);render()}
// ===== SAVE =====
const SID=()=>localStorage.lpid||(localStorage.lpid='u'+Math.random().toString(36).slice(2,10));
function save(q){localStorage.lp=JSON.stringify(S);if(!q)fetch('/api/save',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:SID(),data:S})}).then(r=>r.json()).then(j=>say(j.ok?'Đã lưu ☁️':'Lưu cục bộ')).catch(()=>say('Đã lưu trên máy'))}
async function load(){try{const r=await fetch('/api/load?id='+SID());if(r.ok){S=await r.json();return true}}catch(e){}if(localStorage.lp){S=JSON.parse(localStorage.lp);return true}return false}
// ===== IDEA =====
async function sendIdea(){const t=$('#it').value.trim();if(!t)return;idea={loading:1};render();try{const r=await fetch('/api/ideas',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text:t})});const j=await r.json();idea=j.proposal?{p:j.proposal,t}:{msg:j.msg||j.error,t}}catch(e){idea={msg:'Không kết nối được máy chủ.',t}}render()}
function applyIdea(){const p=idea.p,id='c'+Date.now();
if(p.type=='job')S.custom.jobs.push({id,n:p.name,pay:p.pay,en:p.en||25,h:6,at:'home'});
else if(p.type=='item')S.custom.items.push({id,n:p.name,p:p.price||200000,fx:{mood:p.mood||3},brand:'Ý tưởng',q:3,desc:p.desc});
else if(p.type=='place'){S.custom.places.push(p.name);}
else if(p.type=='npc')S.people.push({n:p.name,role:'Mới',age:25,tr:'thân thiện',rel:30,mood:'ổn',mem:[]});
else S.custom.events.push({name:p.name,desc:p.desc,mood:p.mood});
S.custom.log.push(p.name);log(`Đã thêm vào cuộc sống: ${p.name} (${p.type}).`);idea=null;ideaOpen=false;save(1);render()}
// ===== VẼ =====
function scene(){const [e,n,bg,pr]=PL[S.place],a=ICON[S.last]||'';const slp=S.last=='sleep'&&S.place=='home';
return `<div class="scene"><svg viewBox="0 0 360 190"><rect width="360" height="190" fill="${bg}"/><rect y="140" width="360" height="50" fill="#00000014"/><text x="22" y="62" font-size="38">${e}</text><text x="300" y="60" font-size="34" opacity=".8">${a}</text><text x="250" y="150" font-size="52">${pr}</text>
<g class="${slp?'':'bob'}" transform="${slp?'translate(70 40) rotate(80 90 100)':''}"><circle cx="110" cy="92" r="16" fill="#ffd9b0" stroke="#1f2d4d" stroke-width="3"/><rect x="94" y="110" width="32" height="38" rx="10" fill="#4fc3a1" stroke="#1f2d4d" stroke-width="3"/><circle cx="105" cy="90" r="2" fill="#1f2d4d"/><circle cx="116" cy="90" r="2" fill="#1f2d4d"/></g>
<text x="14" y="182" font-size="14" fill="#1f2d4d" font-weight="700">📍 ${n}</text></svg></div>`}
function hud(){return `<div class="hud"><div class="r"><span>${clock()} · Ngày ${S.day}</span><span>💰 ${fmt(S.money)}</span></div><div class="bars">${ST.slice(1).map(([k,i])=>`<div>${i}<div class="bar ${S.st[k]<25?'low':''}"><i style="width:${S.st[k]}%"></i></div></div>`).join('')}</div></div>`}
function acts(){return D.acts.filter(a=>!a.at||a.at==S.place)}
function tHome(){const hm=S.place=='home',j=J(S.job);let q;
if(hm)q=[['😴 Ngủ tiếp',"act('sleep')"],['🍜 Ăn sáng',"go('restaurant','Bạn bước vào một quán ăn.')"],['💼 Đi làm',j&&j.at?`go('${j.at}')`:"say('Bạn chưa có việc')"],['📱 Kiểm tra điện thoại',"phone()"]];
else q=[...acts().map(a=>[(ICON[a.id]||'▶️')+' '+a.l+(a.m?` (${fmt(-a.m)})`:''),`act('${a.id}')`]),...(j&&j.at==S.place?[['💼 Làm việc','work()']]:[]),['🏠 Về nhà',"go('home')"]];
return `<div class="story"><small>${clock()}</small><br>${esc(S.story)}</div><div class="grid">${q.map(([l,f])=>`<button onclick="${f}">${l}</button>`).join('')}</div>${hm?`<h3>Hoạt động tại nhà</h3><div class="grid">${acts().map(a=>`<button class="alt" onclick="act('${a.id}')">${a.l}</button>`).join('')}</div>`:''}`}
function phone(){if(!has('phone'))return say('Bạn không có điện thoại dùng được.');fx({mood:2});log(['Có tin nhắn từ Linh: "Rảnh đi cafe không?"','Bạn lướt mạng và thấy tin tuyển dụng.','Không có tin nhắn mới.'][Math.floor(R(0,3))]);afterAct();render()}
function tLife(){const j=J(S.job);const b=(l,f)=>`<button class="alt" onclick="${f}">${l}</button>`;
return `<h3>💼 Công việc: ${j.n}</h3><div class="card tag">${S.job=='office'?'Có lương cố định, giờ làm, bị phạt khi trễ, thăng chức sau 5 ca.':S.job=='freelancer'?'Thu nhập không ổn định, cần laptop.':S.job=='shop'?'Cần nhập hàng, trả tiền thuê, có lời/lỗ.':'Hãy tìm việc hoặc tự kinh doanh.'}</div><div class="grid">${j.pay?`<button class="go" onclick="go('${j.at}');work()">Đi làm</button>`:''}${b('Tìm việc',"life('job')")}${b('Làm thêm',"life('part')")}${b('Freelance',"life('free')")}${b('Mở cửa hàng',"life('open')")}${b('Nhập hàng',"life('stock')")}${b('Học nghề',"life('learn')")}${b('Xin nghỉ',"life('quit')")}${S.custom.jobs.map(c=>b('Nghề: '+esc(c.n),`life('c:${c.id}')`)).join('')}</div><h3>🌍 Di chuyển</h3><div class="grid">${Object.keys(PL).map(p=>`<button class="${p==S.place?'go':'alt'}" onclick="go('${p}')">${PL[p][0]} ${PL[p][1]}</button>`).join('')}</div>`}
function tShop(){const it=[...D.shop,...S.custom.items];return `<h3>🛒 Cửa hàng</h3>${it.map(x=>`<div class="card row"><div><b>${esc(x.n)}</b> <span class="tag">${esc(x.brand||'')} · chất lượng ${'★'.repeat(x.q||3)}</span><br><span class="tag">${esc(x.desc||'')}</span></div><button class="sm" onclick="buy('${x.id}')">${fmt(x.p)}</button></div>`).join('')}<h3>🏠 Nhà ở (hiện tại: ${D.homes.find(h=>h.id==S.home).n})</h3>${D.homes.map(h=>`<div class="card row"><div><b>${h.n}</b><br><span class="tag">Thuê ${fmt(h.rent)}/ngày</span></div><button class="sm alt" onclick="rent('${h.id}')">Thuê</button></div>`).join('')}`}
function tPeople(){return S.people.map(p=>`<div class="card"><div class="row"><b>${esc(p.n)}</b><span class="tag">${esc(p.role)} · ${p.age} tuổi · ${esc(p.tr)} · ${p.mood=='giận'?'😠':'🙂'}</span></div><div class="bar" style="background:#dbe8f7"><i style="width:${p.rel}%;background:var(--coral)"></i></div><div class="tag">${p.mem.slice(-3).join(', ')||'Chưa tương tác'}</div>${[['talk','Nói chuyện'],['gift','Tặng quà'],['out','Đi chơi'],['help','Giúp'],['argue','Tranh luận'],['sorry','Xin lỗi'],['date','Hẹn hò']].map(([k,l])=>`<button class="sm alt" onclick="talk('${esc(p.n)}','${k}')">${l}</button>`).join('')}</div>`).join('')}
function tInv(){return `<h3>🎒 Đồ vật</h3>${S.inv.map(i=>`<div class="card row"><b>${esc(i.n)}</b><span class="tag">${i.broken?'Hỏng':'Tốt'} · mua ngày ${i.day}</span></div>`).join('')||'<div class="card tag">Chưa có đồ nào.</div>'}<div class="card tag">Quà: ${S.flags.gift||0} · Thực phẩm: ${S.flags.food||0}</div>`}
function tStatus(){return `<h3>📊 ${esc(S.name)}, ${S.age} tuổi</h3><div class="card">🎯 Mục tiêu: ${esc(S.goal||'Chưa đặt')}<br>💼 ${J(S.job).n} · 🏠 ${D.homes.find(h=>h.id==S.home).n}</div><div class="card">${ST.map(([k,i])=>`<div class="row"><span>${i} ${k}</span><b>${k=='money'?fmt(S.money):S.st[k]}</b></div>`).join('')}</div><div class="grid"><button class="go" onclick="save()">SAVE</button><button class="alt" onclick="load().then(()=>render())">LOAD</button><button class="no" onclick="if(confirm('Bắt đầu cuộc đời mới?')){S=null;render()}">NEW LIFE</button></div><h3>📜 Lịch sử quyết định</h3>${S.log.slice(0,12).map(l=>`<div class="card tag">${esc(l)}</div>`).join('')}`}
function render(){const A=$('#app');
if(!S){A.innerHTML=`<div class="pad" style="text-align:center"><div class="logo">LIFE <b>POV</b></div><p>Bạn muốn sống cuộc đời như thế nào?</p><button class="go" onclick="create(1)">START LIFE</button><button class="alt" onclick="load().then(o=>o?render():say('Chưa có save'))">CONTINUE LIFE</button><button class="alt" onclick="create(0)">CREATE YOUR OWN LIFE</button><div class="tag">${toast}</div></div>`;return}
if(S=='form'){return}
const T={home:tHome,life:tLife,shop:tShop,people:tPeople,inv:tInv,status:tStatus}[tab]();
const nav=[['home','🏠','HOME'],['life','💼','LIFE'],['shop','🛒','SHOP'],['people','👥','PEOPLE'],['inv','🎒','ITEMS'],['status','📊','STATUS']];
A.innerHTML=hud()+scene()+T+(toast?`<div class="card" style="position:fixed;top:70px;left:14px;right:14px;z-index:30;text-align:center;background:var(--sun)">${esc(toast)}</div>`:'')+
`<button class="idea" onclick="ideaOpen=true;render()">💡 IDEA BOX</button><nav>${nav.map(([k,i,l])=>`<a class="${tab==k?'on':''}" onclick="tab='${k}';render()"><span>${i}</span>${l}</a>`).join('')}</nav>`+
(card?`<div class="ev"><div class="card"><div class="tag">📍 ${PL[S.place][1].toUpperCase()}</div><h2 style="margin:6px 0">${card.ic} ${esc(card.t)}</h2><p>Bạn sẽ làm gì?</p>${card.ch.map((c,i)=>`<button class="${i?'alt':'go'}" onclick="pick(${i})">${esc(c[0])}</button>`).join('')}</div></div>`:'')+
(ideaOpen?`<div class="ev"><div class="card"><h2 style="margin:0">💡 Bạn muốn thêm gì vào thế giới này?</h2>${idea&&idea.p?`<p><b>${esc(idea.p.name)}</b> (${idea.p.type})<br>${esc(idea.p.desc)}<br>${idea.p.pay&&idea.p.type=='job'?'Thu nhập: '+fmt(idea.p.pay[0])+' ~ '+fmt(idea.p.pay[1])+'<br>':''}${(idea.p.extras||[]).map(esc).join(', ')}</p><button class="go" onclick="applyIdea()">✅ Thêm vào cuộc sống</button><button class="no" onclick="idea=null;ideaOpen=false;render()">❌ Không thêm</button><button class="alt" onclick="idea=null;render()">✏️ Sửa ý tưởng</button>`:`${['Thêm công việc','Thêm địa điểm','Thêm NPC','Thêm vật phẩm','Thêm sự kiện'].map(c=>`<button class="sm alt" onclick="$('#it').value='${c.slice(5)}: '">+ ${c}</button>`).join('')}<input id="it" placeholder="Nhập ý tưởng..." maxlength="200" value="${idea&&idea.t?esc(idea.t):''}">${idea&&idea.loading?'<p>Đang phân tích…</p>':idea&&idea.msg?`<p>${esc(idea.msg)}</p>`:''}<button class="go" onclick="sendIdea()">Gửi ý tưởng</button><button class="alt" onclick="ideaOpen=false;render()">Đóng</button>`}</div></div>`:'')}
function create(q){const A=$('#app');const f=(l,i,v,t='text')=>`<label>${l}</label><input id="${i}" type="${t}" value="${v}">`;
A.innerHTML=`<div class="pad"><h2>Tạo nhân vật</h2>${f('Tên','n','Minh')}${f('Tuổi','a','22','number')}<label>Giới tính</label><select id="g"><option>Nam</option><option>Nữ</option><option>Khác</option></select>${f('Tiền ban đầu (đ)','m','350000','number')}<label>Nghề nghiệp</label><select id="j"><option value="none">Thất nghiệp</option><option value="office">Nhân viên văn phòng</option><option value="freelancer">Freelancer (cần laptop)</option></select><label>Nơi sống</label><select id="h"><option value="room">Phòng trọ nhỏ</option><option value="flat">Căn hộ</option></select><label>Tính cách</label><select id="t"><option>Hướng ngoại</option><option>Liều lĩnh</option><option>Cẩn thận</option><option>Hướng nội</option></select>${f('Mục tiêu cuộc sống (tùy chọn)','go','')}<button class="go" onclick="start()">Bắt đầu</button></div>`;if(q){start(1)}}
function start(d){const v=i=>$('#'+i)?$('#'+i).value:'';const j=d?'none':v('j');S={name:v('n')||'Bạn',age:+v('a')||22,gender:v('g'),money:d?350000:Math.max(0,+v('m')||0),job:j,home:v('h')||'room',traits:[v('t')||'Cẩn thận'],goal:v('go'),day:1,hour:8,place:'home',st:{...D.start.st},inv:[],people:JSON.parse(JSON.stringify(D.people)),flags:{},cd:{},shifts:0,payMul:1,n:0,log:[],last:'',story:'',custom:{jobs:[],items:[],places:[],events:[],log:[]}};
if(S.job=='freelancer')S.inv.push({id:'laptop',n:'Laptop',day:0});tab='home';log(`Bạn thức dậy. Bạn còn ${fmt(S.money)}.`);render()}
(async()=>{const g=u=>fetch(u).then(r=>r.json());const[l,a,s,p]=await Promise.all([g('/api/life'),g('/api/actions'),g('/api/shop'),g('/api/people')]);D={...l,acts:a,shop:s,people:p};D.acts.push({id:'water',l:'Chỉ uống nước',cat:'food',at:'restaurant',h:.5,m:0,fx:{hunger:3},t:'Bạn chỉ gọi một ly nước.'});render()})();
